In [1]:
import numpy as np
import pandas as pd
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import matplotlib.pyplot as plt
import seaborn as sns
import random

from IPython.display import YouTubeVideo

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping
from keras.models import Model
from keras.callbacks import ReduceLROnPlateau

import cv2

import warnings
warnings.filterwarnings('ignore')

In [2]:
# 1D tensor
a = tf.constant([0, 1, 2, 3])
print(a, '\n')

# 2D tensor
b = tf.constant([[0, 1],
                [2, 3],
                [4, 5]])
print(b, '\n')

# 3D tensor
c = tf.constant([[[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9]],
                  [[10, 11, 12, 13, 14],
                   [15, 16, 17, 18, 19]],
                  [[20, 21, 22, 23, 24],
                   [25, 26, 27, 28, 29]]])
print(c)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32) 

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
